name: Erlang CI

on: [push]

env:
  ERLANG_VERSION: 22.1.8
  REGISTRY: docker.io
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Lint
        run: make wc_lint

      - name: Compile
        run: make wc_compile

      - name: Xref
        run: make wc_xref

      - name: Dialyze
        run: make wc_dialyzer

      - name: Run tests
        run: make wdeps_test
