name: Erlang CI

on: [push]

env:
  ERLANG_VERSION: 22.1.8
  ## For build_utils
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore rebar3 chache
        uses: actions/cache@v1
        with:
          path: ~/.cache/rebar3
          key: rebar3-${{ env.ERLANG_VERSION }}

      - name: Lint
        run: make wc_lint
