name: Erlang CI

on: [push]

env:
  ERLANG_VERSION: 22.1.8
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    container: erlang:22.1.8

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore rebar3 chache
        uses: actions/cache@v1
        with:
          path: ~/.cache/rebar3
          key: rebar3-${{ env.ERLANG_VERSION }}

      - name: Lint
        run: rebar3 lint

      - name: Compile
        run: rebar3 compile

      - name: Xref
        run: rebar3 xref

      - name: Dialyze
        run: rebar3 dialyzer
